version: "3.8"

services:

  frontend:
    build: ./client
    ports:
      - "8080:8080"
    container_name: frontend-docker
    restart: always

  backend:
    build: ./server
    ports:
      - "3000:3000"
    container_name: backend-docker
    restart: always
    