version: "3.8"

services:
  frontend:
    build: ./client
    ports:
      - "8080:8080"
    container_name: frontend-docker
    links:
      - backend

  backend:
    build: ./server
    ports:
      - "8000:8000"
    container_name: backend-docker
    restart: always

