version: "3.8"

services:
  frontend:
    build: ./client
    ports:
      - "8080:8080"
    container_name: frontend-docker
    restart: always

  mongodb:
    container_name: mongo-dev
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  backend:
    build: ./server
    ports:
      - "3000:3000"
    container_name: backend-docker
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/space-odyssey

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
