version: "3"

services:
  frontend:
    build: ./client
    ports:
      - "8080:8080"
    container_name: frontend-docker
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    container_name: backend-docker
    restart: always

